package com.app.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Content generated by hbm2java
 */
public class Content  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private String name;
     private String image;
     private Float price;
     private String sdesc;
     private String tags;
     private Date createdDate;
     private Date lastUpdate;
     private Integer active;

    public Content() {
    }

    public Content(Integer userId, String name, String image, Float price, String sdesc, String tags, Date createdDate, Date lastUpdate, Integer active) {
       this.userId = userId;
       this.name = name;
       this.image = image;
       this.price = price;
       this.sdesc = sdesc;
       this.tags = tags;
       this.createdDate = createdDate;
       this.lastUpdate = lastUpdate;
       this.active = active;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public String getSdesc() {
        return this.sdesc;
    }
    
    public void setSdesc(String sdesc) {
        this.sdesc = sdesc;
    }
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }




}


