package com.app.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Parcels generated by hbm2java
 */
public class Parcels  implements java.io.Serializable {


     private String id;
     private Integer version;
     private String shipmentId;
     private Float length;
     private Float width;
     private Float height;
     private float weight;
     private String predefinedPackage;
     private Date createdAt;
     private String createdBy;
     private Date updatedAt;
     private String updatedBy;

    public Parcels() {
    }

	
    public Parcels(String id, float weight) {
        this.id = id;
        this.weight = weight;
    }
    public Parcels(String id, String shipmentId, Float length, Float width, Float height, float weight, String predefinedPackage, Date createdAt, String createdBy, Date updatedAt, String updatedBy) {
       this.id = id;
       this.shipmentId = shipmentId;
       this.length = length;
       this.width = width;
       this.height = height;
       this.weight = weight;
       this.predefinedPackage = predefinedPackage;
       this.createdAt = createdAt;
       this.createdBy = createdBy;
       this.updatedAt = updatedAt;
       this.updatedBy = updatedBy;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getShipmentId() {
        return this.shipmentId;
    }
    
    public void setShipmentId(String shipmentId) {
        this.shipmentId = shipmentId;
    }
    public Float getLength() {
        return this.length;
    }
    
    public void setLength(Float length) {
        this.length = length;
    }
    public Float getWidth() {
        return this.width;
    }
    
    public void setWidth(Float width) {
        this.width = width;
    }
    public Float getHeight() {
        return this.height;
    }
    
    public void setHeight(Float height) {
        this.height = height;
    }
    public float getWeight() {
        return this.weight;
    }
    
    public void setWeight(float weight) {
        this.weight = weight;
    }
    public String getPredefinedPackage() {
        return this.predefinedPackage;
    }
    
    public void setPredefinedPackage(String predefinedPackage) {
        this.predefinedPackage = predefinedPackage;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


