package com.app.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * ShippingCarriers generated by hbm2java
 */
public class ShippingCarriers implements java.io.Serializable {

	private String id;
	private Integer version;
	private String refId;
	private String name;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createdAt;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date updatedAt;
	private String urlLogo;
	private String code;
	private String serviceName;

	public ShippingCarriers() {
	}

	public ShippingCarriers(String id) {
		this.id = id;
	}

	public ShippingCarriers(String id, String refId, String name, Date createdAt, Date updatedAt, String urlLogo,
			String code, String serviceName) {
		this.id = id;
		this.refId = refId;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.urlLogo = urlLogo;
		this.code = code;
		this.serviceName = serviceName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getRefId() {
		return this.refId;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getUrlLogo() {
		return this.urlLogo;
	}

	public void setUrlLogo(String urlLogo) {
		this.urlLogo = urlLogo;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

}
