package com.app.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Shipments generated by hbm2java
 */
@Entity
public class Shipments implements java.io.Serializable {

	@Id
	@GeneratedValue // (strategy = GenerationType.AUTO)
	@Column(name = "id")
	private String id;
	private Integer version;
	private String fromAddress;
	private String toAddress;
	private String carrierId;

	@Column(nullable = false)
	private BigDecimal appliedFee;
	@Column(nullable = false)
	private BigDecimal actualFee;
	@Column(nullable = false)
	private BigDecimal discount;
	private String currency;
	private String payload;
	private String financialStatus;
	private String shippingStatus;
	private String shippingDesc;
	private String trackingCode;
	private String trackingUrl;
	private String labelUrl;
	private Integer refund;
	private String trackers;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createdAt;
	private String createdBy;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date updatedAt;
	private String updatedBy;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date paymentAt;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date deliveryAt;

	public Shipments() {
	}

	public Shipments(String id) {
		this.id = id;
	}

	public Shipments(String id, String fromAddress, String toAddress, String carrierId, BigDecimal appliedFee,
			BigDecimal actualFee, BigDecimal discount, String currency, String payload, String financialStatus,
			String shippingStatus, String shippingDesc, String trackingCode, String trackingUrl, String labelUrl,
			Integer refund, String trackers, Date createdAt, String createdBy, Date updatedAt, String updatedBy,
			Date paymentAt, Date deliveryAt) {
		this.id = id;
		this.fromAddress = fromAddress;
		this.toAddress = toAddress;
		this.carrierId = carrierId;
		this.appliedFee = appliedFee;
		this.actualFee = actualFee;
		this.discount = discount;
		this.currency = currency;
		this.payload = payload;
		this.financialStatus = financialStatus;
		this.shippingStatus = shippingStatus;
		this.shippingDesc = shippingDesc;
		this.trackingCode = trackingCode;
		this.trackingUrl = trackingUrl;
		this.labelUrl = labelUrl;
		this.refund = refund;
		this.trackers = trackers;
		this.createdAt = createdAt;
		this.createdBy = createdBy;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.paymentAt = paymentAt;
		this.deliveryAt = deliveryAt;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	public BigDecimal getAppliedFee() {
		return this.appliedFee;
	}

	public void setAppliedFee(BigDecimal appliedFee) {
		this.appliedFee = appliedFee;
	}

	public BigDecimal getActualFee() {
		return this.actualFee;
	}

	public void setActualFee(BigDecimal actualFee) {
		this.actualFee = actualFee;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPayload() {
		return this.payload;
	}

	public void setPayload(String payload) {
		this.payload = payload;
	}

	public String getFinancialStatus() {
		return this.financialStatus;
	}

	public void setFinancialStatus(String financialStatus) {
		this.financialStatus = financialStatus;
	}

	public String getShippingStatus() {
		return this.shippingStatus;
	}

	public void setShippingStatus(String shippingStatus) {
		this.shippingStatus = shippingStatus;
	}

	public String getShippingDesc() {
		return this.shippingDesc;
	}

	public void setShippingDesc(String shippingDesc) {
		this.shippingDesc = shippingDesc;
	}

	public String getTrackingCode() {
		return this.trackingCode;
	}

	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	public String getTrackingUrl() {
		return this.trackingUrl;
	}

	public void setTrackingUrl(String trackingUrl) {
		this.trackingUrl = trackingUrl;
	}

	public String getLabelUrl() {
		return this.labelUrl;
	}

	public void setLabelUrl(String labelUrl) {
		this.labelUrl = labelUrl;
	}

	public Integer getRefund() {
		return this.refund;
	}

	public void setRefund(Integer refund) {
		this.refund = refund;
	}

	public String getTrackers() {
		return this.trackers;
	}

	public void setTrackers(String trackers) {
		this.trackers = trackers;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getPaymentAt() {
		return this.paymentAt;
	}

	public void setPaymentAt(Date paymentAt) {
		this.paymentAt = paymentAt;
	}

	public Date getDeliveryAt() {
		return this.deliveryAt;
	}

	public void setDeliveryAt(Date deliveryAt) {
		this.deliveryAt = deliveryAt;
	}

}
