package com.app.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wallets generated by hbm2java
 */
public class Wallets  implements java.io.Serializable {


     private String id;
     private Integer version;
     private String userId;
     private Long balance;
     private Long dueAmount;
     private Long spentAmount;
     private Date createdAt;
     private Date updatedAt;

    public Wallets() {
    }

	
    public Wallets(String id) {
        this.id = id;
    }
    public Wallets(String id, String userId, Long balance, Long dueAmount, Long spentAmount, Date createdAt, Date updatedAt) {
       this.id = id;
       this.userId = userId;
       this.balance = balance;
       this.dueAmount = dueAmount;
       this.spentAmount = spentAmount;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Long getBalance() {
        return this.balance;
    }
    
    public void setBalance(Long balance) {
        this.balance = balance;
    }
    public Long getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(Long dueAmount) {
        this.dueAmount = dueAmount;
    }
    public Long getSpentAmount() {
        return this.spentAmount;
    }
    
    public void setSpentAmount(Long spentAmount) {
        this.spentAmount = spentAmount;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


